"""按层级目录规范整理 products 输出。"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Dict, Iterable, List, TypedDict


class LayerSpec(TypedDict):
    required_dirs: List[str]
    ext_map: Dict[str, str]


LAYER_SPECS: Dict[str, Dict[str, LayerSpec]] = {
    "tb": {
        "L0": {"required_dirs": ["parquet", "json", "figures", "check"], "ext_map": {".parquet": "parquet", ".json": "json", ".png": "figures", ".jpg": "figures", ".jpeg": "figures"}},
        "L1": {"required_dirs": ["json", "figures", "check"], "ext_map": {".json": "json", ".png": "figures", ".jpg": "figures", ".jpeg": "figures"}},
        "L2": {"required_dirs": ["json", "figures", "check"], "ext_map": {".json": "json", ".png": "figures", ".jpg": "figures", ".jpeg": "figures"}},
    },
    "ec": {
        "L0": {"required_dirs": ["parquet", "json", "figures", "check"], "ext_map": {".parquet": "parquet", ".json": "json", ".png": "figures", ".jpg": "figures", ".jpeg": "figures"}},
        "L1": {"required_dirs": ["parquet", "json", "figures", "check"], "ext_map": {".parquet": "parquet", ".json": "json", ".png": "figures", ".jpg": "figures", ".jpeg": "figures"}},
        "L2": {"required_dirs": ["parquet", "json", "figures", "check"], "ext_map": {".parquet": "parquet", ".json": "json", ".png": "figures", ".jpg": "figures", ".jpeg": "figures"}},
        "L3": {"required_dirs": ["parquet", "json", "figures", "artifacts", "check"], "ext_map": {".parquet": "parquet", ".json": "json", ".png": "figures", ".jpg": "figures", ".jpeg": "figures", ".npy": "artifacts"}},
    },
}


def _ensure_dirs(base: Path, names: Iterable[str]) -> None:
    for name in names:
        (base / name).mkdir(parents=True, exist_ok=True)


def _write_contract(layer_dir: Path, subsystem: str, layer: str, payload: str, required_dirs: List[str]) -> None:
    contract = {
        "payload": payload,
        "subsystem": subsystem,
        "layer": layer,
        "required_dirs": required_dirs,
        "notes": "auto-generated by organize_products",
    }
    (layer_dir / "pipeline_contract.json").write_text(json.dumps(contract, ensure_ascii=False, indent=2), encoding="utf-8")


def _move_stray_files(layer_dir: Path, ext_map: Dict[str, str], moved: List[str]) -> None:
    for fp in layer_dir.iterdir():
        if not fp.is_file():
            continue
        if fp.name == "pipeline_contract.json":
            continue
        target_subdir = ext_map.get(fp.suffix.lower())
        if not target_subdir:
            target_subdir = "artifacts"
            (layer_dir / target_subdir).mkdir(parents=True, exist_ok=True)
        dst = layer_dir / target_subdir / fp.name
        shutil.move(str(fp), str(dst))
        moved.append(str(dst))


def organize_payload(product_root: Path, payload: str) -> Dict[str, object]:
    payload_root = Path(product_root) / payload
    moved: List[str] = []

    for subsystem, layers in LAYER_SPECS.items():
        for layer, spec in layers.items():
            layer_dir = payload_root / subsystem / layer
            layer_dir.mkdir(parents=True, exist_ok=True)
            _ensure_dirs(layer_dir, spec["required_dirs"])
            _write_contract(layer_dir, subsystem, layer, payload, spec["required_dirs"])
            _move_stray_files(layer_dir, spec["ext_map"], moved)

    return {"payload": payload, "moved_files": moved, "n_moved": len(moved)}
